// Code generated by ent, DO NOT EDIT.

package call

const (
	// Label holds the string label denoting the call type in the database.
	Label = "call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldBlockCount holds the string denoting the block_count field in the database.
	FieldBlockCount = "block_count"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the call in the database.
	Table = "calls"
	// UserTable is the table that holds the user relation/edge. The primary key declared below.
	UserTable = "user_calls"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
)

// Columns holds all SQL columns for call fields.
var Columns = []string{
	FieldID,
	FieldDuration,
	FieldBlockCount,
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"user_id", "call_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
