// Code generated by ent, DO NOT EDIT.

package call

const (
	// Label holds the string label denoting the call type in the database.
	Label = "call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldBlockCount holds the string denoting the block_count field in the database.
	FieldBlockCount = "block_count"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the call in the database.
	Table = "calls"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "calls"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_calls"
)

// Columns holds all SQL columns for call fields.
var Columns = []string{
	FieldID,
	FieldDuration,
	FieldBlockCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "calls"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_calls",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
