// Code generated by ent, DO NOT EDIT.

package call

import (
	"calling-bill/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDuration), v))
	})
}

// BlockCount applies equality check predicate on the "block_count" field. It's identical to BlockCountEQ.
func BlockCount(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBlockCount), v))
	})
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDuration), v))
	})
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDuration), v))
	})
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...int) predicate.Call {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDuration), v...))
	})
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...int) predicate.Call {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDuration), v...))
	})
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDuration), v))
	})
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDuration), v))
	})
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDuration), v))
	})
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDuration), v))
	})
}

// BlockCountEQ applies the EQ predicate on the "block_count" field.
func BlockCountEQ(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBlockCount), v))
	})
}

// BlockCountNEQ applies the NEQ predicate on the "block_count" field.
func BlockCountNEQ(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBlockCount), v))
	})
}

// BlockCountIn applies the In predicate on the "block_count" field.
func BlockCountIn(vs ...int) predicate.Call {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldBlockCount), v...))
	})
}

// BlockCountNotIn applies the NotIn predicate on the "block_count" field.
func BlockCountNotIn(vs ...int) predicate.Call {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldBlockCount), v...))
	})
}

// BlockCountGT applies the GT predicate on the "block_count" field.
func BlockCountGT(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBlockCount), v))
	})
}

// BlockCountGTE applies the GTE predicate on the "block_count" field.
func BlockCountGTE(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBlockCount), v))
	})
}

// BlockCountLT applies the LT predicate on the "block_count" field.
func BlockCountLT(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBlockCount), v))
	})
}

// BlockCountLTE applies the LTE predicate on the "block_count" field.
func BlockCountLTE(v int) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBlockCount), v))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UserTable, UserPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UserTable, UserPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Call) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Call) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Call) predicate.Call {
	return predicate.Call(func(s *sql.Selector) {
		p(s.Not())
	})
}
