// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CallsColumns holds the columns for the "calls" table.
	CallsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "duration", Type: field.TypeInt},
		{Name: "block_count", Type: field.TypeInt},
		{Name: "user_calls", Type: field.TypeInt},
	}
	// CallsTable holds the schema information for the "calls" table.
	CallsTable = &schema.Table{
		Name:       "calls",
		Columns:    CallsColumns,
		PrimaryKey: []*schema.Column{CallsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "calls_users_calls",
				Columns:    []*schema.Column{CallsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 32},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CallsTable,
		UsersTable,
	}
)

func init() {
	CallsTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
