// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CallsColumns holds the columns for the "calls" table.
	CallsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "duration", Type: field.TypeInt},
		{Name: "block_count", Type: field.TypeInt},
	}
	// CallsTable holds the schema information for the "calls" table.
	CallsTable = &schema.Table{
		Name:       "calls",
		Columns:    CallsColumns,
		PrimaryKey: []*schema.Column{CallsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 32},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// UserCallsColumns holds the columns for the "user_calls" table.
	UserCallsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "call_id", Type: field.TypeInt},
	}
	// UserCallsTable holds the schema information for the "user_calls" table.
	UserCallsTable = &schema.Table{
		Name:       "user_calls",
		Columns:    UserCallsColumns,
		PrimaryKey: []*schema.Column{UserCallsColumns[0], UserCallsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_calls_user_id",
				Columns:    []*schema.Column{UserCallsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_calls_call_id",
				Columns:    []*schema.Column{UserCallsColumns[1]},
				RefColumns: []*schema.Column{CallsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CallsTable,
		UsersTable,
		UserCallsTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UserCallsTable.ForeignKeys[0].RefTable = UsersTable
	UserCallsTable.ForeignKeys[1].RefTable = CallsTable
}
